export const products = [
  {
    name: "Hoodie",
    size: "R",
    price: "22.76 USD",
    description: "5 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 1,
  },
  {
    name: "Hoodie",
    size: "XL",
    price: "45.28 USD",
    description: "10 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 2,
  },
  {
    name: "Hoodie",
    size: "M",
    price: "341.79 USD",
    description: "3 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 3,
  },
  {
    name: "Hoodie",
    size: "XXL",
    price: "9.87 USD",
    description: "4 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 4,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "300.99 USD",
    description: "10 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 5,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
  {
    name: "Hoodie",
    size: "S",
    price: "115.22 USD",
    description: "12 sec ago",
    image: require("../assets/images/hi.jpg"),
    id: 6,
  },
];
