export const products = [
  {
    name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
    size: "R",
    price: "22.76",
    currency: "NZD",
    description: "5 sec ago",
    image: require("../assets/images/ProductImg.webp"),
    id: 1,
  },
  {
    name: "90's fsgsdfgfg4gefdgdfg",
    size: "XL",
    price: "45.28",
    currency: "NZD",
    description: "10 sec ago",
    image: require("../assets/images/ProductImg.webp"),
    id: 2,
  },
  {
    name: "90's A34534gdfg",
    size: "M",
    price: "341.79",
    currency: "NZD",
    description: "3 sec ago",
    image: require("../assets/images/ProductImg.webp"),
    id: 3,
  },
  {
    name: "90's sdf36fgt",
    size: "XXL",
    price: "9.87",
    currency: "NZD",
    description: "4 sec ago",
    image: require("../assets/images/ProductImg.webp"),
    id: 4,
  },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "300.99",
  //     currency: "NZD",
  //     description: "10 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 5,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
  //   {
  //     name: "90's Austrian Trophy Compact Ski France Made High Neck Sweatshirt",
  //     size: "S",
  //     price: "115.22",
  //     currency: "NZD",
  //     description: "12 sec ago",
  //     image: require("../assets/images/ProductImg.webp"),
  //     id: 6,
  //   },
];
